name: pytorch
channels:
  - defaults
  - conda-forge
  - fastai
  - pytorch
dependencies:
  - abseil-cpp=20211102.0=hd77b12b_0
  - absl-py=1.4.0=py38haa95532_0
  - aiohttp=3.8.3=py38h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py38haa95532_0
  - attrs=22.1.0=py38haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py38haa95532_0
  - bottleneck=1.3.5=py38h080aedc_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - c-ares=1.19.0=h2bbff1b_0
  - ca-certificates=2023.08.22=haa95532_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2023.7.22=py38haa95532_0
  - cffi=1.15.1=py38h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38haa95532_0
  - colorama=0.4.6=py38haa95532_0
  - comm=0.1.2=py38haa95532_0
  - cryptography=41.0.2=py38hac1b9e3_0
  - cudatoolkit=11.3.1=h280eb24_10
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython-blis=0.7.9=py38h080aedc_0
  - debugpy=1.6.7=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fastcore=1.5.29=py_0
  - fastdownload=0.0.7=py_0
  - fastprogress=1.0.3=py_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.3.3=py38h2bbff1b_0
  - giflib=5.2.1=h8cc25b3_3
  - grpc-cpp=1.48.2=hfe90ff0_1
  - grpcio=1.48.2=py38hfe90ff0_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.4=py38haa95532_0
  - importlib-metadata=6.0.0=py38haa95532_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=6.1.0=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=6.25.0=py38h9909e9c_0
  - ipython=8.12.2=py38haa95532_0
  - jedi=0.18.1=py38haa95532_1
  - jinja2=3.1.2=py38haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jupyter_client=8.1.0=py38haa95532_0
  - jupyter_core=5.3.0=py38haa95532_0
  - krb5=1.20.1=h5b6d351_0
  - langcodes=3.3.0=pyhd3eb1b0_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.4=hd77b12b_0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=h906ac69_1
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - lz4-c=1.9.4=h2bbff1b_0
  - markdown=3.4.1=py38haa95532_0
  - markupsafe=2.1.1=py38h2bbff1b_0
  - matplotlib-base=3.7.2=py38h4ed8f06_0
  - matplotlib-inline=0.1.6=py38haa95532_0
  - mkl=2023.1.0=h6b88ed4_46357
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.6=py38hf11a4ad_1
  - mkl_random=1.2.2=py38hf11a4ad_1
  - multidict=6.0.2=py38h2bbff1b_0
  - munkres=1.1.4=py_0
  - nest-asyncio=1.5.6=py38haa95532_0
  - numexpr=2.8.4=py38h7b80656_1
  - numpy=1.24.3=py38h79a8e48_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - oauthlib=3.2.2=py38haa95532_0
  - openssl=3.0.12=h2bbff1b_0
  - packaging=23.1=py38haa95532_0
  - pandas=2.0.3=py38h4ed8f06_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py38hd77b12b_0
  - pip=23.2.1=py38haa95532_0
  - platformdirs=3.10.0=py38haa95532_0
  - ply=3.11=py38_0
  - pooch=1.7.0=py38haa95532_0
  - prompt-toolkit=3.0.36=py38haa95532_0
  - psutil=5.9.0=py38h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38haa95532_1
  - pyjwt=2.4.0=py38haa95532_0
  - pyopenssl=23.2.0=py38haa95532_0
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.17=h1aa4202_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=1.10.1=py3.8_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py38haa95532_0
  - pywin32=305=py38h2bbff1b_0
  - pyyaml=6.0.1=py38h2bbff1b_0
  - pyzmq=25.1.0=py38hd77b12b_0
  - qt-main=5.15.2=h19c9488_10
  - re2=2022.04.01=hd77b12b_0
  - requests=2.31.0=py38haa95532_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.3.0=py38h4ed8f06_0
  - setuptools=58.0.4=py38haa95532_0
  - shellingham=1.5.0=py38haa95532_0
  - sip=6.7.12=py38hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py38haa95532_0
  - spacy-legacy=3.0.12=py38haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - tensorboard-plugin-wit=1.8.1=py38haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - tomli=2.0.1=py38haa95532_0
  - torchaudio=0.10.1=py38_cu113
  - torchvision=0.11.2=py38_cu113
  - tornado=6.3.2=py38h2bbff1b_0
  - traitlets=5.7.1=py38haa95532_0
  - typing-extensions=4.7.1=py38haa95532_0
  - typing_extensions=4.7.1=py38haa95532_0
  - urllib3=1.26.16=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.2.3=py38haa95532_0
  - wheel=0.38.4=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38haa95532_2
  - xz=5.4.2=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - yarl=1.8.1=py38h2bbff1b_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.11.0=py38haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - annotated-types==0.5.0
      - blis==0.7.10
      - catalogue==2.0.9
      - confection==0.1.3
      - contourpy==1.1.0
      - cymem==2.0.7
      - fastai==2.7.12
      - fonttools==4.42.1
      - gdstk==0.9.52
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - importlib-resources==6.0.1
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.7.3
      - murmurhash==1.0.9
      - opencv-python==4.12.0.88
      - pathy==0.10.2
      - preshed==3.0.8
      - protobuf==3.19.6
      - pydantic==2.3.0
      - pydantic-core==2.6.3
      - pyparsing==3.1.1
      - scipy==1.10.1
      - smart-open==6.4.0
      - spacy==3.6.1
      - spacy-loggers==1.0.5
      - srsly==2.4.7
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - thinc==8.1.12
      - threadpoolctl==3.2.0
      - tqdm==4.66.1
      - typer==0.9.0
      - wasabi==1.1.2
prefix: D:\Anaconda\envs\pytorch
